on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: pnpm --version
      - uses: actions/checkout@v3
      - run: pnpm install
      - run: node app.js
